Document: freeipa
Title: Debian freeipa Manual
Author: <insert document author here>
Abstract: This manual describes what freeipa is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/freeipa/freeipa.sgml.gz

Format: postscript
Files: /usr/share/doc/freeipa/freeipa.ps.gz

Format: text
Files: /usr/share/doc/freeipa/freeipa.text.gz

Format: HTML
Index: /usr/share/doc/freeipa/html/index.html
Files: /usr/share/doc/freeipa/html/*.html


